// Materials data for individual detail pages
export const materials = [
  {
    slug: "agarwood",
    name: "Agarwood",
    chinese: "Chenxiang (沉香)",
    latin: "Aquilaria sinensis",
    category: "Woods",
    image: "/images/material-agarwood.jpg",
    intro: "The most prized incense material on earth — dark, resinous wood formed only when an Aquilaria tree is wounded or infected.",
    profile: "Warm, sweet balsamic with complex resinous depth",
    uses: "Heating on charcoal or electric warmer, premium blends, meditation",
    history: "Traded in China since the Han Dynasty, once worth more than gold; central to Song Dynasty literati culture.",
    relatedArticle: "/blog/agarwood-king-of-incense/",
    relatedLabel: "Agarwood: The King of Chinese Incense",
  },
  {
    slug: "sandalwood",
    name: "Sandalwood",
    chinese: "Tanxiang (檀香)",
    latin: "Santalum album",
    category: "Woods",
    image: "/images/material-sandalwood.jpg",
    intro: "A creamy, warm, sweet wood — the classic foundation of incense practice, formed naturally in mature Santalum trees.",
    profile: "Creamy, warm, sweet with a subtle milky smoothness",
    uses: "Daily burning, sticks, blending base note, meditation",
    history: "A staple of meditation practice for centuries; its heartwood takes 15-30 years to develop fragrance.",
    relatedArticle: "/blog/agarwood-vs-sandalwood/",
    relatedLabel: "Agarwood vs Sandalwood: A Complete Comparison",
  },
  {
    slug: "frankincense",
    name: "Frankincense",
    chinese: "Ruxiang (乳香)",
    latin: "Boswellia sacra",
    category: "Resins",
    image: "/images/material-frankincense.jpg",
    intro: "A resin with a citrus-pine opening and warm, balsamic depth — one of the classic 'middle note' resins.",
    profile: "Citrus-pine opening with warm, balsamic depth",
    uses: "Heating on charcoal, blending middle notes, incense competitions",
    history: "Arrived in China via the Silk Road during the Han Dynasty; prized in Buddhist ritual.",
    relatedArticle: "/blog/incense-tools-utensils/",
    relatedLabel: "Essential Incense Tools and Utensils",
  },
  {
    slug: "clove-bud",
    name: "Clove Bud",
    chinese: "Dingxiang (丁香)",
    latin: "Syzygium aromaticum",
    category: "Spices",
    image: "/images/material-clove.jpg",
    intro: "A sharp, warming, numbing spice with sweet undertones — a potent top-note accent in blends.",
    profile: "Sharp, warming, numbing spice with sweet undertones",
    uses: "Blending top notes, traditional medicine, heating",
    history: "One of the 'exotic spices' that reached China through maritime trade.",
    relatedArticle: "/blog/art-of-blending-incense/",
    relatedLabel: "The Art of Blending Incense: Hehe Xiang",
  },
  {
    slug: "cassia",
    name: "Cassia",
    chinese: "Rougui (肉桂)",
    latin: "Cinnamomum cassia",
    category: "Spices",
    image: "/images/material-cassia.jpg",
    intro: "Sweet, woody cinnamon with a pungent edge — a warming spice used in both incense and medicine.",
    profile: "Sweet, woody cinnamon with a pungent edge",
    uses: "Blending, warming preparations, traditional medicine",
    history: "A native Chinese cinnamon, documented in classical incense manuals.",
    relatedArticle: "/blog/history-of-chinese-incense/",
    relatedLabel: "A Brief History of Chinese Incense",
  },
  {
    slug: "patchouli",
    name: "Patchouli",
    chinese: "Guanghuoxiang (广藿香)",
    latin: "Pogostemon cablin",
    category: "Herbs",
    image: "/images/material-patchouli.jpg",
    intro: "An earthy, musky, wine-like herb with deep bitter-sweetness — grounding and complex.",
    profile: "Earthy, musky, wine-like with a deep bitter-sweetness",
    uses: "Blending, herbal preparations, traditional medicine",
    history: "A key herb in Chinese materia medica, also used in incense blends for its grounding depth.",
    relatedArticle: "/blog/art-of-blending-incense/",
    relatedLabel: "The Art of Blending Incense: Hehe Xiang",
  },
  {
    slug: "camphor",
    name: "Camphor",
    chinese: "Zhangnao (樟脑)",
    latin: "Cinnamomum camphora",
    category: "Resins",
    image: "/images/material-camphor.jpg",
    intro: "A cooling, medicinal, sharp crystalline resin with a camphoraceous bite.",
    profile: "Cooling, medicinal, sharp with a camphoraceous bite",
    uses: "Blending top notes, cooling accents, traditional medicine",
    history: "Distilled from the camphor tree, a traditional cooling agent in Chinese pharmacy.",
    relatedArticle: "/blog/agarwood-king-of-incense/",
    relatedLabel: "Agarwood: The King of Chinese Incense",
  },
  {
    slug: "spikenard",
    name: "Spikenard",
    chinese: "Gansong (甘松)",
    latin: "Nardostachys jatamansi",
    category: "Herbs",
    image: "/images/material-spikenard.jpg",
    intro: "An earthy, animalic, musty root with sweet woody undertones — rare and deeply grounding.",
    profile: "Earthy, animalic, musty with sweet woody undertones",
    uses: "Blending, traditional medicine, spiritual preparations",
    history: "Mentioned in ancient texts across Asia; a treasured aromatic in classical blends.",
    relatedArticle: "/blog/history-of-chinese-incense/",
    relatedLabel: "A Brief History of Chinese Incense",
  },
  {
    slug: "borneol",
    name: "Borneol",
    chinese: "Bingpian (冰片)",
    latin: "Dryobalanops aromatica",
    category: "Resins",
    image: "/images/material-borneol.jpg",
    intro: "A cool, piercingly fresh crystalline resin with a minty-camphor lift — the 'guide' ingredient in blends.",
    profile: "Cool, piercingly fresh with a minty-camphor lift",
    uses: "Harmonizing blends, top-note lift, traditional medicine",
    history: "A precious 'guide' (shi) ingredient in the jun-chen blending system.",
    relatedArticle: "/blog/art-of-blending-incense/",
    relatedLabel: "The Art of Blending Incense: Hehe Xiang",
  },
  {
    slug: "licorice",
    name: "Licorice",
    chinese: "Gancao (甘草)",
    latin: "Glycyrrhiza uralensis",
    category: "Herbs",
    image: "/images/material-licorice.jpg",
    intro: "A sweet, earthy, enveloping root with a slight menthol finish — the great harmonizer of blends.",
    profile: "Sweet, earthy, enveloping with a slight menthol finish",
    uses: "Harmonizing blends, extending fragrance, traditional medicine",
    history: "Called the 'harmonizer' in Chinese medicine; a small amount transforms a blend.",
    relatedArticle: "/blog/art-of-blending-incense/",
    relatedLabel: "The Art of Blending Incense: Hehe Xiang",
  },
];
