// German materials data for individual detail pages
export const materialsDe = [
  {
    slug: "agarwood",
    name: "Agarholz",
    chinese: "Chenxiang (沉香)",
    latin: "Aquilaria sinensis",
    category: "Hölzer",
    image: "/images/material-agarwood.jpg",
    intro: "Das kostbarste Räuchermaterial der Erde — dunkles, harziges Holz, das nur entsteht, wenn ein Aquilaria-Baum verletzt oder infiziert wird.",
    profile: "Warm, süß-balsamisch mit komplexer harziger Tiefe",
    uses: "Erhitzen auf Holzkohle oder elektrischer Lampe, Premium-Mischungen, Meditation",
    history: "Seit der Han-Dynastie in China gehandelt, einst mehr wert als Gold; zentral für die Gelehrtenkultur der Song-Dynastie.",
    relatedArticle: "/de/blog/agarwood-king-of-incense/",
    relatedLabel: "Agarholz: Der König des chinesischen Räucherns",
  },
  {
    slug: "sandalwood",
    name: "Sandelholz",
    chinese: "Tanxiang (檀香)",
    latin: "Santalum album",
    category: "Hölzer",
    image: "/images/material-sandalwood.jpg",
    intro: "Ein cremiges, warmes, süßes Holz — das klassische Fundament der Räucherpraxis, natürlich im reifen Santalum-Baum gebildet.",
    profile: "Cremig, warm, süß mit subtiler milchiger Glätte",
    uses: "Tägliches Räuchern, Stäbchen, Basisnote für Mischungen, Meditation",
    history: "Seit Jahrhunderten fester Bestandteil der Meditationspraxis; sein Kernholz braucht 15–30 Jahre, um Duft zu entwickeln.",
    relatedArticle: "/de/blog/agarwood-vs-sandalwood/",
    relatedLabel: "Agarholz vs. Sandelholz: Ein vollständiger Vergleich",
  },
  {
    slug: "frankincense",
    name: "Weihrauch",
    chinese: "Ruxiang (乳香)",
    latin: "Boswellia sacra",
    category: "Harze",
    image: "/images/material-frankincense.jpg",
    intro: "Ein Harz mit zitrusartiger Kiefernöffnung und warmer balsamischer Tiefe — eines der klassischen „Mittelnoten“-Harze.",
    profile: "Zitrus-Kiefern-Öffnung mit warmer balsamischer Tiefe",
    uses: "Erhitzen auf Holzkohle, Mittelnoten beim Mischen, Räucherwettbewerbe",
    history: "Gelangte während der Han-Dynastie über die Seidenstraße nach China; im buddhistischen Ritual geschätzt.",
    relatedArticle: "/de/blog/incense-tools-utensils/",
    relatedLabel: "Wesentliche Räucherwerkzeuge und -utensilien",
  },
  {
    slug: "clove-bud",
    name: "Gewürznelke",
    chinese: "Dingxiang (丁香)",
    latin: "Syzygium aromaticum",
    category: "Gewürze",
    image: "/images/material-clove.jpg",
    intro: "Ein scharfes, wärmendes, betäubendes Gewürz mit süßen Untertönen — ein kräftiger Kopfnoten-Akzent in Mischungen.",
    profile: "Scharf, wärmend, betäubend mit süßen Untertönen",
    uses: "Kopfnoten beim Mischen, traditionelle Medizin, Erhitzen",
    history: "Eines der „exotischen Gewürze“, die über den Seehandel nach China gelangten.",
    relatedArticle: "/de/blog/art-of-blending-incense/",
    relatedLabel: "Die Kunst des Räuchermischens: Hehe Xiang",
  },
  {
    slug: "cassia",
    name: "Kassia",
    chinese: "Rougui (肉桂)",
    latin: "Cinnamomum cassia",
    category: "Gewürze",
    image: "/images/material-cassia.jpg",
    intro: "Süßes, holziges Zimt mit durchdringender Schärfe — ein wärmendes Gewürz für Räucherwerk und Medizin.",
    profile: "Süß, holzig mit durchdringender Schärfe",
    uses: "Mischen, wärmende Zubereitungen, traditionelle Medizin",
    history: "Ein einheimischer chinesischer Zimt, dokumentiert in klassischen Räucherhandbüchern.",
    relatedArticle: "/de/blog/history-of-chinese-incense/",
    relatedLabel: "Eine kurze Geschichte des chinesischen Räucherns",
  },
  {
    slug: "patchouli",
    name: "Patschuli",
    chinese: "Guanghuoxiang (广藿香)",
    latin: "Pogostemon cablin",
    category: "Kräuter",
    image: "/images/material-patchouli.jpg",
    intro: "Ein erdiges, moschusartiges, weinartiges Kraut mit tiefer Bittersüße — erdend und komplex.",
    profile: "Erdig, moschusartig, weinartig mit tiefer Bittersüße",
    uses: "Mischen, Kräuterzubereitungen, traditionelle Medizin",
    history: "Ein Schlüsselkraut der chinesischen Materia Medica, auch in Räuchermischungen für seine erdende Tiefe geschätzt.",
    relatedArticle: "/de/blog/art-of-blending-incense/",
    relatedLabel: "Die Kunst des Räuchermischens: Hehe Xiang",
  },
  {
    slug: "camphor",
    name: "Kampfer",
    chinese: "Zhangnao (樟脑)",
    latin: "Cinnamomum camphora",
    category: "Harze",
    image: "/images/material-camphor.jpg",
    intro: "Ein kühlendes, medizinisches, scharfes kristallines Harz mit kampferartigem Biss.",
    profile: "Kühlend, medizinisch, scharf mit kampferartigem Biss",
    uses: "Kopfnoten beim Mischen, kühlende Akzente, traditionelle Medizin",
    history: "Aus dem Kampferbaum destilliert, ein traditionelles Kühlmittel der chinesischen Pharmazie.",
    relatedArticle: "/de/blog/agarwood-king-of-incense/",
    relatedLabel: "Agarholz: Der König des chinesischen Räucherns",
  },
  {
    slug: "spikenard",
    name: "Nardenwurzel",
    chinese: "Gansong (甘松)",
    latin: "Nardostachys jatamansi",
    category: "Kräuter",
    image: "/images/material-spikenard.jpg",
    intro: "Eine erdige, animalische, moschusartige Wurzel mit süß-holzigen Untertönen — selten und tief erdend.",
    profile: "Erdig, animalisch, moschusartig mit süß-holzigen Untertönen",
    uses: "Mischen, traditionelle Medizin, spirituelle Zubereitungen",
    history: "In antiken Texten ganz Asiens erwähnt; ein geschätztes Aroma in klassischen Mischungen.",
    relatedArticle: "/de/blog/history-of-chinese-incense/",
    relatedLabel: "Eine kurze Geschichte des chinesischen Räucherns",
  },
  {
    slug: "borneol",
    name: "Borneol",
    chinese: "Bingpian (冰片)",
    latin: "Dryobalanops aromatica",
    category: "Harze",
    image: "/images/material-borneol.jpg",
    intro: "Ein kühles, durchdringend frisches kristallines Harz mit minzig-kampferartigem Auftrieb — die „Führer“-Zutat in Mischungen.",
    profile: "Kühl, durchdringend frisch mit minzig-kampferartigem Auftrieb",
    uses: "Harmonisieren von Mischungen, Kopfnoten-Auftrieb, traditionelle Medizin",
    history: "Eine kostbare „Führer“-(Shi-)Zutat im Jun-Chen-Mischsystem.",
    relatedArticle: "/de/blog/art-of-blending-incense/",
    relatedLabel: "Die Kunst des Räuchermischens: Hehe Xiang",
  },
  {
    slug: "licorice",
    name: "Süßholz",
    chinese: "Gancao (甘草)",
    latin: "Glycyrrhiza uralensis",
    category: "Kräuter",
    image: "/images/material-licorice.jpg",
    intro: "Eine süße, erdige, umhüllende Wurzel mit leichtem Menthol-Finish — der große Harmonisierer der Mischungen.",
    profile: "Süß, erdig, umhüllend mit leichtem Menthol-Finish",
    uses: "Harmonisieren von Mischungen, Verlängern des Dufts, traditionelle Medizin",
    history: "In der chinesischen Medizin „Harmonisierer“ genannt; eine kleine Menge verwandelt eine Mischung.",
    relatedArticle: "/de/blog/art-of-blending-incense/",
    relatedLabel: "Die Kunst des Räuchermischens: Hehe Xiang",
  },
];
