export const products = [
  {
    slug: "qing-lin-sui",
    name: "青麟髓 · Qing Lin Sui",
    en: "Green Dragon Marrow",
    type: "Traditional formula · New release",
    notes: "Cooling · Clear · Resinous",
    desc: "A new release with a striking cooling profile — cool, clear, and resinous, designed for slow warm elevation.",
    formula: "Traditional formula (Xiang Pu lineage), newly released",
    image: "/images/xiangwan-01.jpg",
    extraImages: ["/images/xiangwan-02.jpg"],
  },
  {
    slug: "chun-yue-hu-die",
    name: "春月蝴蝶香 · Spring Moon Butterfly",
    en: "Spring Moon Butterfly",
    type: "Traditional formula",
    notes: "Soft · Floral · Elegant",
    desc: "A gentle spring-floral blend following the original historical formula, soft and elegant on the burner.",
    formula: "Faithful to the original formula",
    image: "/images/xiangwan-02.jpg",
    extraImages: ["/images/xiangwan-01.jpg"],
  },
  {
    slug: "han-jian-ning",
    name: "汉建宁宫中香 · Han Jianning Palace",
    en: "Han Jianning Palace Incense",
    type: "Traditional formula",
    notes: "Rich · Warm · Composed",
    desc: "A palace incense from the Han dynasty tradition, made close to the original recipe — rich, warm, and composed.",
    formula: "Close to the original formula",
    image: "/images/xiangwan-03.jpg",
    extraImages: ["/images/xiangwan-02.jpg"],
  },
  {
    slug: "kuang-ye-you-lan",
    name: "旷野幽兰 · Wild Orchid",
    en: "Wild Orchid of the Wilderness",
    type: "Original creation",
    notes: "Green · Quiet · Wild",
    desc: "An original blend — a lone orchid in the open field, green, quiet, and slightly wild.",
    formula: "Original creation",
    image: "/images/xiangwan-01.jpg",
    extraImages: ["/images/xiangwan-03.jpg"],
  },
  {
    slug: "shou-yang-gong-zhu",
    name: "寿阳公主梅花香 · Plum Blossom",
    en: "Princess Shouyang Plum Blossom",
    type: "Traditional formula",
    notes: "Crisp · Cool · Poetic",
    desc: "Plum blossom incense in the tradition of Princess Shouyang — crisp, cool, and poetic, faithful to the original formula.",
    formula: "Faithful to the original formula",
    image: "/images/xiangwan-02.jpg",
    extraImages: ["/images/xiangwan-01.jpg"],
  },
  {
    slug: "xun-ling-shi-li",
    name: "荀令十里香 · Ten-Mile Fragrance",
    en: "Xun Ling's Ten-Mile Fragrance",
    type: "Traditional formula",
    notes: "Refined · Lingering · Legendary",
    desc: "The legendary fragrance said to linger for ten li — made following the original formula, with a lasting, refined character.",
    formula: "Faithful to the original formula",
    image: "/images/xiangwan-03.jpg",
    extraImages: ["/images/xiangwan-02.jpg"],
  },
  {
    slug: "lili-marlene",
    name: "莉莉玛莲 · Lili Marleen",
    en: "Lili Marleen",
    type: "Original creation",
    notes: "Smoky · Magnetic · Unforgettable",
    desc: "An original blend honoring Marlene Dietrich — an irreplaceable legend of the screen: smoky, magnetic, unforgettable.",
    formula: "Original creation, dedicated to Marlene Dietrich",
    image: "/images/xiangwan-01.jpg",
    extraImages: ["/images/xiangwan-03.jpg"],
  },
];
